### ISSUE TITLE
CORS 

### ISSUE THREAD

**Issue by pmaasz** [derlangsamelukas/mubble#2]
Access to script at 'file:///Users/[PATH TO PROJECT]/mubble/run.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

**Comment by derlangsamelukas** [comment]
Iam using ES6 modules within the browser, so these modules have the resitrction that they cannot be loaded from a _file://.*_ url (I think modules are fetched via a XHR Request under the hood and these have the same restriction for security reasons).
You need to serve the files over a web server (a simple file server is sufficient).
